name: build

on:
  push:
    branches:
      - main
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: unit-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Run Go Tests
        run: |
          go test -v ./... > test-results.txt
          cat test-results.txt

  build:
    name: build-image
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build image and export to tar
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Containerfile
          platforms: linux/amd64,linux/arm64
          push: false
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}
          outputs: type=oci,dest=/tmp/image.tar
      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: image-artifact
          path: /tmp/image.tar

  push:
    name: push-image
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    needs: build
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: image-artifact
          path: /tmp
      - name: Load image from tar
        run: docker load --input /tmp/image.tar
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Determine image tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}:${{ github.sha }}
          for TAG in ${{ steps.meta.outputs.tags }}; do
            docker tag $IMAGE_ID $TAG
            docker push $TAG
          done
