name: test

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: unit-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Run Go Tests
        run: |
          go test -v ./... > test-results.txt
          cat test-results.txt
